
let STATE={exams:[],students:[],results:[],settings:{},essayItems:[],currentEssay:null,rot:0,zoom:1};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
async function jfetch(url,opt){const r=await fetch(url,opt);const t=await r.text();let d;try{d=JSON.parse(t)}catch{d={success:false,message:t}}if(!r.ok)throw Error(d.message||r.statusText);return d}
$('#nav').onclick=e=>{const b=e.target.closest('button[data-panel]');if(!b)return;$$('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.panel').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.panel).classList.add('active');$('#pageTitle').textContent=b.textContent.replace(/^[^A-Za-zÀ-ỹ]+/,'').trim()}
function n(v){return Number(v||0)} function esc(v){return String(v??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
async function loadAll(){const d=await jfetch('/api/state');STATE.exams=d.exams||[];STATE.students=d.students||[];STATE.settings=d.settings||{};renderExams();renderStudents();fillSettings();$('#sExam').textContent=STATE.exams.length;$('#sStudent').textContent=STATE.students.length;await refreshResults(false)}
function renderExams(){$('#examRows').innerHTML=STATE.exams.map(x=>`<tr><td><b>${esc(x.id)}</b></td><td>${esc(x.title)}</td><td>${esc(x.settings?.durationMinutes||'')} phút</td><td><span class="badge green">Đang dùng</span></td><td><a class="btn" href="exam.html?exam=${encodeURIComponent(x.id)}" target="_blank">Xem</a></td></tr>`).join('')||'<tr><td colspan=5>Chưa có đề.</td></tr>'}
function renderStudents(){$('#studentRows').innerHTML=STATE.students.map(x=>`<tr><td>${esc(x.studentId)}</td><td><b>${esc(x.studentName)}</b></td><td>${esc(x.className)}</td><td>${esc(x.birthDate)}</td><td>${esc(x.parentPhone)}</td><td>${esc(x.email)}</td></tr>`).join('')||'<tr><td colspan=6>Chưa có học sinh.</td></tr>'}
function fillSettings(){const f=$('#settingsForm'),s=STATE.settings||{};['school','teacher','passScore','appsScriptUrl'].forEach(k=>f.elements[k].value=s[k]??'');const a=s.antiCheat||{};['tabSwitch','copy','paste','rightClick','devtoolsWarning','camera'].forEach(k=>f.elements[k].checked=!!a[k])}
async function refreshResults(show=true){try{const url=STATE.settings.appsScriptUrl;if(!url)throw Error('Chưa có URL Apps Script');const r=await fetch(url+'?action=list&_='+Date.now());const d=await r.json();STATE.results=(d.results||[]).map(normalizeResult);$('#apiState').textContent='Google Sheets đã kết nối';$('#apiState').style.background='#e7f8ed';if(show)alert('Đã đồng bộ '+STATE.results.length+' lượt nộp.')}catch(e){STATE.results=JSON.parse(localStorage.getItem('examResults')||'[]').map(normalizeResult);$('#apiState').textContent='Đang dùng dữ liệu cục bộ';if(show)alert('Không đồng bộ được Google Sheets: '+e.message)}renderResults();renderDashboard()}
function normalizeResult(r){return {...r,studentId:r.studentId||r.maHS||'',studentName:r.studentName||r.hoTen||'',className:r.className||r.lop||'',examId:r.examId||r.maDe||'',score:n(r.score??r.diem),maxScore:n(r.maxScore||10),submitTime:r.submitTime||r.thoiGianNop||'',detail:Array.isArray(r.detail)?r.detail:[],auditLog:Array.isArray(r.auditLog)?r.auditLog:[]}}
function renderResults(){const q=$('#resultSearch').value.toLowerCase();const rows=STATE.results.filter(r=>[r.studentId,r.studentName,r.className,r.examId].join(' ').toLowerCase().includes(q));$('#resultRows').innerHTML=rows.map(r=>`<tr><td><b>${esc(r.studentId)} - ${esc(r.studentName)}</b></td><td>${esc(r.className)}</td><td>${esc(r.examId)}</td><td><b>${r.score}/${r.maxScore}</b></td><td>${n(r.correct)}/${n(r.total)}</td><td>${r.submitTime?new Date(r.submitTime).toLocaleString('vi-VN'):''}</td><td><button class="btn" onclick='showAudit(${JSON.stringify(r.auditLog||[])})'>${(r.auditLog||[]).length} sự kiện</button></td></tr>`).join('')||'<tr><td colspan=7>Chưa có kết quả.</td></tr>'}
function showAudit(log){alert(log.length?log.map(x=>`${x.time||''}: ${x.type||x.event||''}`).join('\n'):'Không có nhật ký.')}
function renderDashboard(){const a=STATE.results.map(r=>r.score).filter(Number.isFinite),cnt=a.length,mean=cnt?a.reduce((x,y)=>x+y,0)/cnt:0,sorted=[...a].sort((x,y)=>x-y),median=cnt?(cnt%2?sorted[(cnt-1)/2]:(sorted[cnt/2-1]+sorted[cnt/2])/2):0,pass=a.filter(x=>x>=n(STATE.settings.passScore||5)).length;$('#sSubmit').textContent=cnt;$('#sMean').textContent=mean.toFixed(2);$('#summaryStats').innerHTML=`<p>Trung vị: <b>${median.toFixed(2)}</b></p><p>Cao nhất: <b>${cnt?Math.max(...a):0}</b></p><p>Thấp nhất: <b>${cnt?Math.min(...a):0}</b></p><p>Tỉ lệ đạt: <b>${cnt?(pass*100/cnt).toFixed(1):0}%</b></p>`;drawHistogram(a);renderQuestionStats()}
function drawHistogram(a){const c=$('#scoreChart'),dpr=devicePixelRatio||1,w=c.clientWidth||500,h=c.clientHeight||280;c.width=w*dpr;c.height=h*dpr;const x=c.getContext('2d');x.scale(dpr,dpr);x.clearRect(0,0,w,h);const bins=Array(10).fill(0);a.forEach(v=>bins[Math.min(9,Math.max(0,Math.floor(v))) ]++);const mx=Math.max(1,...bins),pad=32,bw=(w-pad*2)/10;x.strokeStyle='#b8c7da';x.beginPath();x.moveTo(pad,10);x.lineTo(pad,h-pad);x.lineTo(w-pad,h-pad);x.stroke();bins.forEach((v,i)=>{const bh=(h-pad-20)*v/mx;x.fillStyle='#2f6ec1';x.fillRect(pad+i*bw+4,h-pad-bh,bw-8,bh);x.fillStyle='#52657c';x.font='12px Segoe UI';x.fillText(String(i),pad+i*bw+bw/2-3,h-10)})}
function renderQuestionStats(){const m={};STATE.results.forEach(r=>(r.detail||[]).forEach(d=>{const k=`${r.examId||''}-${d.id}`;m[k]??={id:d.id,exam:r.examId,n:0,ok:0};m[k].n++;if(d.isCorrect)m[k].ok++}));$('#questionStats').innerHTML=Object.values(m).map(x=>{const p=x.n?100*x.ok/x.n:0,cls=p>=70?'green':p>=40?'amber':'red',txt=p>=70?'Tốt':p>=40?'Cần chú ý':'Câu khó';return `<tr><td>${esc(x.exam)} · Câu ${x.id}</td><td>${x.n}</td><td>${p.toFixed(1)}%</td><td><span class="badge ${cls}">${txt}</span></td></tr>`}).join('')||'<tr><td colspan=4>Chưa có dữ liệu chi tiết.</td></tr>'}
$('#studentImport').onsubmit=async e=>{e.preventDefault();const d=await jfetch('/api/students/import',{method:'POST',body:new FormData(e.target)});alert(d.message);await loadAll()}
async function clearStudents(){if(!confirm('Xóa toàn bộ danh sách học sinh?'))return;await jfetch('/api/students/clear',{method:'POST'});await loadAll()}
function downloadFile(u){location.href=u}
function exportResultsCsv(){const head=['Mã HS','Họ tên','Lớp','Mã đề','Điểm','Điểm tối đa','Số câu đúng','Tổng câu','Thời gian nộp'];const lines=[head,...STATE.results.map(r=>[r.studentId,r.studentName,r.className,r.examId,r.score,r.maxScore,r.correct,r.total,r.submitTime])].map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(','));const b=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='ket_qua_thi.csv';a.click();URL.revokeObjectURL(a.href)}
$('#settingsForm').onsubmit=async e=>{e.preventDefault();const f=e.target,s={school:f.school.value,teacher:f.teacher.value,passScore:n(f.passScore.value),appsScriptUrl:f.appsScriptUrl.value.trim(),antiCheat:{}};['tabSwitch','copy','paste','rightClick','devtoolsWarning','camera'].forEach(k=>s.antiCheat[k]=f.elements[k].checked);const d=await jfetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(s)});$('#settingsMsg').innerHTML='<div class="notice">'+esc(d.message)+'</div>';STATE.settings=s}
async function pingApi(){try{const u=$('#settingsForm').appsScriptUrl.value.trim();const r=await fetch(u+'?action=ping&_='+Date.now());const d=await r.json();alert(d.success?'Kết nối thành công':'Phản hồi: '+JSON.stringify(d))}catch(e){alert('Lỗi: '+e.message)}}
async function serverAction(u){try{const d=await jfetch(u,{method:'POST'});$('#deployMsg').innerHTML='<div class="notice">'+esc(d.message)+(d.file?'<br><b>'+esc(d.file)+'</b>':'')+'</div>'}catch(e){alert(e.message)}}
$('#restoreForm').onsubmit=async e=>{e.preventDefault();if(!confirm('Khôi phục sẽ ghi đè dữ liệu hiện tại. Tiếp tục?'))return;const d=await jfetch('/api/restore',{method:'POST',body:new FormData(e.target)});alert(d.message);location.reload()}
function prepareEssay(){STATE.essayItems=[];STATE.results.forEach(r=>(r.detail||[]).filter(d=>d.type==='essay').forEach(d=>STATE.essayItems.push({r,d})));$('#essayList').innerHTML=STATE.essayItems.map((x,i)=>`<div class="essay-item" onclick="selectEssay(${i})"><b>${esc(x.r.studentName||x.r.studentId)}</b><br><span class="muted">${esc(x.r.className)} · ${esc(x.r.examId)} · Câu ${x.d.id}</span></div>`).join('')||'<p>Không có bài tự luận.</p>'}
function selectEssay(i){STATE.currentEssay=STATE.essayItems[i];$$('.essay-item').forEach((x,k)=>x.classList.toggle('active',k===i));const {r,d}=STATE.currentEssay;$('#essayTitle').textContent=`${r.studentName||r.studentId} – Câu ${d.id}`;STATE.rot=0;STATE.zoom=1;let imgs=(d.images||[]).filter(x=>x.dataUrl||x.url);$('#essayContent').innerHTML=`<p><b>Bài gõ:</b> ${esc(d.given||'')}</p>`+(imgs.length?imgs.map((x,j)=>`<img id="essayImg${j}" class="essay-image" src="${x.dataUrl||x.url}">`).join(''):'<p class="muted">Không có ảnh.</p>');const rub=Array.isArray(d.rubric)?d.rubric:[];$('#rubricBox').innerHTML='<h3>Rubric</h3>'+(rub.length?rub.map((z,k)=>`<div class="rubric-row"><input type="checkbox" data-point="${n(z.point||z.points||0)}" onchange="sumRubric()"><span>${esc(z.text||z.description||'Tiêu chí '+(k+1))}</span><b>${n(z.point||z.points||0)} điểm</b></div>`).join(''):`<label>Điểm giáo viên</label><input id="manualScore" type="number" step=".25" min="0" max="${d.maxPoint||10}">`)+`<p><b>Tổng: <span id="rubricTotal">0</span>/${d.maxPoint||10}</b></p><button class="btn primary" onclick="saveGrade()">Lưu điểm</button>`}
function sumRubric(){let s=0;$$('#rubricBox input[type=checkbox]:checked').forEach(x=>s+=n(x.dataset.point));$('#rubricTotal').textContent=s.toFixed(2)}
async function saveGrade(){const {r,d}=STATE.currentEssay||{};if(!r)return;let score=$('#manualScore')?n($('#manualScore').value):n($('#rubricTotal').textContent);const payload={key:[r.studentId,r.examId,d.id,r.submitTime].join('|'),studentId:r.studentId,examId:r.examId,questionId:d.id,score,maxPoint:d.maxPoint||0,savedAt:new Date().toISOString()};const x=await jfetch('/api/manual-grade',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});alert(x.message)}
function rotateImage(deg){STATE.rot+=deg;applyImg()}function zoomImage(z){STATE.zoom=Math.max(.2,STATE.zoom+z);applyImg()}function applyImg(){$$('.essay-image').forEach(x=>x.style.transform=`rotate(${STATE.rot}deg) scale(${STATE.zoom})`)}
window.loadAll=loadAll;window.refreshResults=refreshResults;window.renderResults=renderResults;window.showAudit=showAudit;window.clearStudents=clearStudents;window.downloadFile=downloadFile;window.exportResultsCsv=exportResultsCsv;window.pingApi=pingApi;window.serverAction=serverAction;window.prepareEssay=prepareEssay;window.selectEssay=selectEssay;window.sumRubric=sumRubric;window.saveGrade=saveGrade;window.rotateImage=rotateImage;window.zoomImage=zoomImage;
loadAll().catch(e=>alert('Không tải được Teacher Edition: '+e.message));
